import numpy as np
zero_D_array=np.array(20)
print(zero_D_array)
print(zero_D_array.ndim)
one_D_array=np.array([1,2,3,4,5,6,7])
print(one_D_array)
print(one_D_array.ndim)
two_D_array=np.array([[1,2,3],[4,5,6]])
print(two_D_array)
print("how to access 2 and 4 into two_D_array...")
print(two_D_array[0][1],two_D_array[1][0])
print(two_D_array.ndim)
three_D_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_D_array)
print("how to access 2 ,4 ,6and 8 into three_D_array...")
print(three_D_array[0][0][1],three_D_array[0][1][1],three_D_array[1][0][1],three_D_array[1][1][1])
print(three_D_array.ndim)
print("We can assign the dimensions....")
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)