# Generated by Django 3.2.7 on 2021-11-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app30', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
