# Generated by Django 3.1.3 on 2020-12-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_discription', models.CharField(max_length=1000)),
                ('product_date', models.DateField()),
            ],
        ),
    ]
