# Generated by Django 3.1.3 on 2020-12-14 15:52

from django.db import migrations, models
from django.db.models import AutoField


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201202_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(default='', max_length=50)),
                ('eloc', models.CharField(default='', max_length=50)),
                ('esal', models.IntegerField(default=0)),
            ],
        ),
    ]
