# Generated by Django 3.1.3 on 2020-12-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='no user name', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=13)),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='Mumbai', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(default='no name', max_length=50),
        ),
    ]
