# Generated by Django 3.2.7 on 2021-11-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app30', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporters',
            new_name='reporter',
        ),
    ]
