# Generated by Django 3.2.7 on 2021-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app30', '0002_rename_reporters_article_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ManyToManyField(to='app30.Reporter'),
        ),
    ]
