# Generated by Django 3.2.7 on 2021-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app30', '0003_auto_20211109_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['color_name'],
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_name', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('shoes_color', models.ManyToManyField(to='app30.Color')),
            ],
            options={
                'ordering': ['shoes_name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
        migrations.AddField(
            model_name='shoes',
            name='shoes_shop',
            field=models.ManyToManyField(to='app30.Shop'),
        ),
    ]
