# Generated by Django 3.2.7 on 2021-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
